apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-web
spec:
  selector:
    matchLabels:
      run: app
  replicas: 1
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: shopping-lops
          image: pokawa/shopping-lops
          ports:
            - containerPort: 3000
