apiVersion: v1
kind: Service
metadata:
  name: shopping-db
  labels:
    run: shopping-deployment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    run: shopping-deployment
