apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-web-deployment
spec:
  selector:
    matchLabels:
      run: shopping-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: shopping-deployment
    spec:
      containers:
        - name: shopping-web
          image: yellocabins/shopping-lops
          ports:
            - containerPort: 3000