apiVersion: v1
kind: Service
metadata:
  name: shopping-svc
  labels:
    app: shopping-lops
spec:
  type: NodePort
  selector:
    app: shopping-lops
  ports:
    - nodePort: 31806
      port: 80
      targetPort: 3000
      protocol: TCP
