apiVersion: v1
kind: Service
metadata:
  name: shopping-svc
  labels:
    run: shopping
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    run: shopping
