apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport-svc
  labels:
    app: mysql-server
spec:
  type: NodePort
  selector:
    data: shopping-lops
  ports:
    - port: 80
      targetPort: 3086
      protocol: TCP
